engines:

  eslint:
    enabled: true
    channel: "eslint-3"
    config:
     config: ./.eslintrc
     extensions:
     - .js
     checks:
       import/no-unresolved:
         enabled: false
       import/extensions:
         enabled: false
       import/no-named-as-default-member:
         enabled: false

ratings:
  paths:
    - "src/**"
    - "src/**/*"
    - "**.js"
