engines:

  eslint:
    enabled: true
    channel: "eslint-3"
    config:
     config: ./.eslintrc
       checks:
         import/no-unresolved:
           enabled: false
         import/extensions:
           enabled: false
         import/no-named-as-default-member:
           enabled: false
     extensions:
     - .js
ratings:
  paths:
    - "src/**"
    - "src/**/*"
    - "**.js"
