sudo: required

language: node_js
node_js:
  - "6"

install:
  - npm install
addons:
  code_climate:
    repo_token: 1e3ede5f1df39fc6ae35a0128f9e61fceb61a6f4

after_script:
  - codeclimate-test-reporter < lcov.info
