language: node_js

git:
  depth: 10

node_js:
  - 4

addons:
  code_climate:
    repo_token: 1e3ede5f1df39fc6ae35a0128f9e61fceb61a6f4

install:
   - npm install
   - npm install -g firebase-tools

script:
   - npm run test
   - npm run build

after_script:
   - firebase deploy --token=${FIREBASE_API_TOKEN}
   - codeclimate-test-reporter < lcov.info
